[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = true

[kubernetes.context_aliases]
#"cluster_name" = "alias"

[gcloud]
disabled = false
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
[gcloud.project_aliases]
inner-synapse-358216 = 'Goxo Last Dance'
