#! /bin/sh
# Initialize clipboard
clipmenud &

# Initialize Look and feel
#xrandr -s 1280x800 &
feh --bg-fill /home/ajramos/Pictures/city.jpg &
$HOME/.config/polybar/launch.sh --cuts
picom &

# Initialize other utilities
tilix &
pulseaudio --start

pgrep -x sxhkd > /dev/null || sxhkd &

