#! /bin/sh

# Initialize clipboard
clipmenud &

# Initialize Look and feel
#xrandr -s 1280x800 &
feh --bg-fill /home/ajramos/Pictures/city.jpg &
$HOME/.config/polybar/launch.sh 
picom &

# Initialize other utilities
tilix &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

# Colors
source $HOME/.config/bspwm/colors.cfg
bspc config focused_border_color            "$primary"
bspc config active_border_color             "$green"
bspc config normal_border_color             "$background"
bspc config urgent_border_color             "$foreground"

SPACES=$(bspc query -D)
for SPACE in $SPACES
do
	bspc config -d ${SPACE} window_gap 8
	bspc config -d ${SPACE} top_padding 10
	bspc config -d ${SPACE} bottom_padding 10
	bspc config -d ${SPACE} left_padding 10
	bspc config -d ${SPACE} right_padding 10
done

bspc config automatic_scheme		 	spiral
bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false
bspc config single_monocle       	true
bspc config focus_follows_pointer true


bspc desktop ^1 -1 monocle
bspc desktop ^2 -1 monocle
bspc desktop ^5 -1 monocle
bspc desktop ^6 -1 monocle
bspc desktop ^9 -1 monocle
bspc desktop ^10 -1 monocle

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a code-oss desktop='^3'
bspc rule -a robo3t desktop='^4'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a Cawbird desktop='^5'
bspc rule -a Slack desktop='^6'
bspc rule -a Gimp-2.10 desktop='^7'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# set Desktop 7 to start with floating windows
FLOATING_DEKSTOP_ID=$(bspc query -D -d '^7')
bspc subscribe node_manage | while read -a msg ; do
	desk_id=${msg[2]}
	wid=${msg[3]}
	[ "$FLOATING_DEKSTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
