code --install-extension 42Crunch.vscode-openapi
code --install-extension avisdsouza.grule-syntax
code --install-extension be5invis.toml
code --install-extension burkeholland.simple-react-snippets
code --install-extension castwide.solargraph
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension discountry.react-redux-react-router-snippets
code --install-extension donjayamanne.javadebugger
code --install-extension DotJoshJohnson.xml
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eg2.vscode-npm-script
code --install-extension EQuimper.react-native-react-redux
code --install-extension eriklynd.json-tools
code --install-extension esbenp.prettier-vscode
code --install-extension ferdelamad.styled-snippets
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension googlecloudtools.cloudcode
code --install-extension hashicorp.terraform
code --install-extension humao.rest-client
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension jasonnutter.search-node-modules
code --install-extension jonkwheeler.styled-components-snippets
code --install-extension joshjg.generate-react-component
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kiteco.kite
code --install-extension leizongmin.node-module-intellisense
code --install-extension lonefy.vscode-JS-CSS-HTML-formatter
code --install-extension marp-team.marp-vscode
code --install-extension mhutchie.git-graph
code --install-extension mohsen1.prettify-json
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-es
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.node-debug2
code --install-extension msjsdiag.vscode-react-native
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension Stephanvs.dot
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.nodejs-extension-pack
code --install-extension wingrunr21.vscode-ruby
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
