code --install-extension 42crunch.vscode-openapi
code --install-extension castwide.solargraph
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension coenraads.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension dotjoshjohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension humao.rest-client
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension juanblanco.solidity
code --install-extension lonefy.vscode-js-css-html-formatter
code --install-extension marp-team.marp-vscode
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-es
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension timonwong.shellcheck
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wingrunr21.vscode-ruby
code --install-extension xabikos.javascriptsnippets
